### ISSUE TITLE
ToDo Backend Admin Frontend endpoints

### ISSUE THREAD

**Issue by Maxi1324** [ZID-Automat/Backend-ZIDAutomat#68]
- [x] - Data-Analysis(Infos/Statistiken)
- [ ] - Buchhaltungsdaten anzeigen(discuss)
- [x] - Zustand anzeigen(Was ist gerade im automat(krasse Grafik(kann ziel)))
- [x] - Hinzufügen !!!
- [ ] - Entfernen !!!
- [x] - Update !!!
- [x] - Inventar Anzeigen(Was für Artikel gibts) !!!
- [x] - Nachfüllen(discuss)
